return{}
-- return({
--   "Kurama622/llm.nvim",
--   dependencies = { "nvim-lua/plenary.nvim", "MunifTanjim/nui.nvim" },
--   cmd = { "LLMSessionToggle", "LLMSelectedTextHandler" },
--   config = function()
--     require("llm").setup({
--       -- 其他配置...
--       url = "https://api.deepseek.com/chat/completions",
--       model = "deepseek-chat",
--       api_type = "openai",
--       fetch_key = function()
--         return switch("enable_deepseek")
--       end,
--       -- 其他配置...
--     })
--   end,
--   keys = {
--     { "<leader>ac", mode = "n", "<cmd>LLMSessionToggle<cr>" },
--     { "<leader>ae", mode = "v", "<cmd>LLMSelectedTextHandler 请解释下面这段代码<cr>" },
--     { "<leader>t", mode = "x", "<cmd>LLMSelectedTextHandler 英译汉<cr>" },
--   },
-- })
